
# This file was *autogenerated* from the file foo.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6)
var("m", "n", "o", "p", "q", "r")

a = matrix(SR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], 
                [_sage_const_0 , _sage_const_1 , _sage_const_1 ], 
                [_sage_const_0 , _sage_const_0 , _sage_const_1 ]])

b = matrix(SR, [[_sage_const_1 , _sage_const_1 , _sage_const_0 ], 
                [_sage_const_0 , _sage_const_1 , _sage_const_0 ], 
                [_sage_const_0 , _sage_const_0 , _sage_const_1 ]])

c = matrix(SR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], 
                [_sage_const_0 , _sage_const_1 , -_sage_const_1 ], 
                [_sage_const_0 , _sage_const_0 , _sage_const_1 ]])

d = matrix(SR, [[_sage_const_1 , -_sage_const_1 , _sage_const_0 ], 
                [_sage_const_0 , _sage_const_1 , _sage_const_0 ], 
                [_sage_const_0 , _sage_const_0 , _sage_const_1 ]])

e = matrix(SR, [[_sage_const_1 , _sage_const_0 , _sage_const_1 ], 
                [_sage_const_0 , _sage_const_1 , _sage_const_0 ], 
                [_sage_const_0 , _sage_const_0 , _sage_const_1 ]])

print e**_sage_const_7  * a ** _sage_const_2  * b ** _sage_const_6 

# really just want. (x * y == z) for x, y, z in Z iff (these semigroups elements are equal to those semigroup elements)

'''
So let's start with 2 * 3 == 6

maybe instead of equal to the identity, we could do equal to the square of a thing?
'''

f = a**_sage_const_2 
g = b**_sage_const_3 
h = c**_sage_const_2 
i = d**_sage_const_3 
# print (f * g)
# print (h * i)
# print (f * g * c * d)
# print ((e**6).inverse() * (f * g)).inverse()


'''
we want
[1 3 0]     [1 0 6]
[0 1 2] M = [0 1 0]
[0 0 1]     [0 0 1]

which would just be...
'''

# print (f * g).solve_right(matrix([[1, 3, 6], [0, 1, 2], [0, 0, 1]]))

'''
so this looks like
[1 3 0]     [1 3 6]
[0 1 2] M = [0 1 2]
[0 0 1]     [0 0 1]

or rather

a**x * b**y * e**z = a**x * b**y * e**(x+y)

meh this just reduces to
e**(x+y) == e**z

ok but sure i can get natural number multiplication this way
how to encode the sign without using negatives in the matrix elements?

yah this is cool though. turns addition into multiplication
THIS DOESN"T WORK

maybe i could get something like
[1 6 6]
[0 1 6]
[0 0 1]

this would just be
'''

# print f * g
# print
# print (f * g).solve_right(matrix([[1, 6, 6], [0, 1, 6], [0, 0, 1]]))

ooo = matrix(SR, [[_sage_const_1 , m, _sage_const_0 ], 
                  [_sage_const_0 , _sage_const_1 , _sage_const_0 ], 
                  [_sage_const_0 , _sage_const_0 , _sage_const_1 ]])

ppp = matrix(SR, [[_sage_const_1 , _sage_const_0 , _sage_const_0 ], 
                  [_sage_const_0 , _sage_const_1 , r], 
                  [_sage_const_0 , _sage_const_0 , _sage_const_1 ]])

# print ooo * ppp
# print e**4
# print ooo**3

'''
Ok, I think we can do this. I don't think we need to ever care about negative
multiplications ever. Integer solutions to Diophantine equations is equivalent
to natural number solutions (the proof is on wikipedia page for Hilbert's tenth).
And we don't need to check if P(x1..xn) = a, we can move all the negative coeffs 
over to the other side. So we're asking if P(x1..xn) == a + Q(x1..xn).

So we can build a systems of equations for each of these polynomials. It becomes
a bunch of additions and a bunch of multiplications, where everything is positive.

Then we can just use 
e = matrix(SR, [[1, 0, 1], 
                [0, 1, 0], 
                [0, 0, 1]])

and ask if e**(x+y) == e**z? Fuck, no. Not quite.
'''
# print e**(2 + 3)
# print (a ** 3) * (b ** 2) * (e ** 2)

